name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /var/www/frontend-development/
        remote_host: ${{secrets.SERVER_IP}}
        remote_user: ${{secrets.REMOTE_USER}}
        remote_key: ${{ secrets.DEPLOY_KEY }}